name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        architecture: [x86_64, arm64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential upx-ucl patchelf
          pip install pyinstaller

      - name: Build executable
        run: |
          pyinstaller --onefile pylight.py
        env:
          PYINSTALLER_ARCH: ${{ matrix.architecture }}

      - name: Upload to GitHub
        uses: actions/upload-artifact@v2
        with:
          name: pylight-${{ matrix.architecture }}
          path: dist/pylight

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download built executables
        uses: actions/download-artifact@v2
        with:
          name: pylight-x86_64
          path: dist/x86_64
      - name: Download built executables
        uses: actions/download-artifact@v2
        with:
          name: pylight-arm64
          path: dist/arm64

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/x86_64/pylight
            dist/arm64/pylight
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
